Add `expectStringResponse`
NoRedInk/haskell-libraries pull request #57
Opened 2022-11-08 13:53 UTC by adauguet

2022-11-10 11:00 UTC, adauguet commented
We could consider changing to `metadataHeaders :: Dict Text (NonEmpty Text)`.

2022-11-17 07:17 UTC, stoeffel commented on nri-http/src/Http.hs
> +mkMetadata response =
🎨 NamedFieldPuns is enabled in package.yaml. Why not pattern match for `reponseStatus` and `responseHeaders` here instead of `let`?

2022-11-17 07:51 UTC, stoeffel commented on nri-http/src/Http.hs
> +            Internal.ExpectText -> Ok bodyAsText
Should we use https://hackage.haskell.org/package/text-2.0.1/docs/Data-Text-Encoding.html#v:decodeUtf8-39-
here?

2022-11-17 07:52 UTC, stoeffel commented on nri-http/src/Http.hs
> +            Internal.ExpectText -> Ok bodyAsText
maybe everywhere where we docedUtf8 rn?

2022-11-17 07:53 UTC, stoeffel requested changes
Looks great!
I'd appreciate some tests before merging though.
One additional thing, I wonder if we should use decodeUtf8' instead of decodeUtf8 everywhere were we expect Text

2022-11-17 08:01 UTC, stoeffel commented on nri-http/src/Http.hs
> +mkMetadata response =
nevermind: `Response` is opaque.

2022-11-17 12:25 UTC, stoeffel approved these changes
Looks great!
Thank you!

2022-11-17 12:25 UTC, merged